Working
BSGreaves/reindeer pull request #1
Opened 2017-01-25 02:23 UTC by BSGreaves

Done!
Remind me to ask for feedback on how to get html back into the div. For instance, here I added "<br>" to the end of each array item so that they would break properly on the page.

2017-01-26 21:19 UTC, drdreed commented on main.js
> +console.log(finalReindeer);
Please remove unnecessary `console.log().`

2017-01-26 21:20 UTC, DevDreed requested changes
Looks good just remove unneeded console statements.

2017-01-26 21:22 UTC, drdreed commented
Also instead of using `<br>` using an unordered list `<ul><li></li></ul>` would make it look more like the example.

2017-01-26 21:36 UTC, BSGreaves commented
@drdreed Hey, do I need to tag you in each comment, or only once in each Repo when I open a pull request?
Can you recommend a method of getting an <ul> plus the <li> elements into the div using innerHTML? Right now I'm pushing little pieces of HTML into the array but I suspect what I'm doing is kinda sloppy.
Appreciate it!

2017-01-26 21:52 UTC, drdreed commented
Something like this should work.

```
let string = "<ul>";
for (let x = 0; x < array.length; x++){
	string += "<li>Something in Here</li>";
}
string += "</ul>";

domElement.innerHTML = string;
```

2017-01-28 15:12 UTC, DevDreed approved these changes
👍

2017-01-28 15:13 UTC, BSGreaves commented
Test

2017-01-28 15:13 UTC, merged

2017-02-08 01:23 UTC, morecallan commented
@drdreed @BSGreaves - just wanted to call you guys out for one of the best big sib/little sib reviews out there. keep it up, homies.

2017-02-08 02:22 UTC, BSGreaves commented
Hey, yeah @drdreed is an awesome buddy. Lots of great insights. Sorry if you're subtly hinting for me to close branches... I tend to make updates, close branches, and update Dustin all at once, then wait a week before doing it again.